### ISSUE TITLE
How to handle code runner errors which are not the user's fault?

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Backend-Re#15]
In at least one case it happened that an exception was thrown due to a network error in the connection to the docker workers, which caused the user submission to fail (see example stacktrace at the end).

In that case we simply log this, but the submission is still considered as valid, which in case of a graded submission is not fair. Also this causes an endless loop, since we never set a console output which causes our zombie submissions. 

https://github.com/mp-access/Backend/blob/520740e3513cf70623915f4af016f50c9c1ca26b/src/main/java/ch/uzh/ifi/access/student/evaluation/process/step/DelegateCodeExecStep.java#L47-L69

We should consider flagging these submissions, so that they: 
1) do not count, in case they are a graded submission
2) we can tell the user it was a problem with the system and not their code and to please try again.

My idea is:
1) Mark the submission as invalid
2) Add a systemError flag. In the frontend we show some generic message to try again.
3) Send the event FINISHED to the state machine to avoid endless loop (or simply set an empty string console, so that the state machine can continue normally).

What do you think @soyabeen?

**Network error example:** 
```logs
2019-12-02 02:37:29,343 ERROR [b7ee1f5b6383760d] 1 -- [eval-worker-2] c.u.i.a.s.e.p.step.DelegateCodeExecStep: Something unexpected happened while attempting to run student code
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.UnknownHostException: info1-worker.ifi.uzh.ch: Temporary failure in name resolution
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2848)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2723)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:742)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:724)
	at ch.uzh.ifi.access.coderunner.CodeRunner.createAndRunContainer(CodeRunner.java:117)
	at ch.uzh.ifi.access.coderunner.CodeRunner.attachVolumeAndRunBash(CodeRunner.java:82)
	at ch.uzh.ifi.access.student.evaluation.runner.SubmissionCodeRunner.executeSmokeTest(SubmissionCodeRunner.java:83)
	at ch.uzh.ifi.access.student.evaluation.runner.SubmissionCodeRunner.execSubmissionForExercise(SubmissionCodeRunner.java:61)
	at ch.uzh.ifi.access.student.evaluation.process.step.DelegateCodeExecStep.execute(DelegateCodeExecStep.java:50)
	at ch.uzh.ifi.access.student.evaluation.EvalProcessService.executeStep(EvalProcessService.java:100)
	at ch.uzh.ifi.access.student.evaluation.EvalProcessService.fireEvalProcessExecutionAsync(EvalProcessService.java:74)
	at ch.uzh.ifi.access.student.evaluation.EvalProcessService$$FastClassBySpringCGLIB$$ad6fe16d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.springframework.cloud.sleuth.instrument.async.TraceAsyncAspect.traceBackgroundThread(TraceAsyncAspect.java:67)
	at jdk.internal.reflect.GeneratedMethodAccessor324.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.PerformanceMonitorInterceptor.invokeUnderTrace(PerformanceMonitorInterceptor.java:62)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.UnknownHostException: info1-worker.ifi.uzh.ch: Temporary failure in name resolution
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2721)
	... 33 common frames omitted
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.UnknownHostException: info1-worker.ifi.uzh.ch: Temporary failure in name resolution
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	... 4 common frames omitted
Caused by: java.net.UnknownHostException: info1-worker.ifi.uzh.ch: Temporary failure in name resolution
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at com.spotify.docker.client.shaded.org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at com.spotify.docker.client.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at com.spotify.docker.client.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at com.spotify.docker.client.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at com.spotify.docker.client.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 common frames omitted
```

**Comment by ofvalentine** [comment]
Submissions are now saved prior to evaluation with a default `valid = false` status. After the evaluation the status is changed to `valid = true` if the submission is:
* Not graded
* Graded and has been assigned points (i.e. `submissions.points != null`)

A submission is assigned points in 3 ways:
1.  A docker exception is raised and the error message contains the string "timeout"  -> `points = 0.0`
2. The docker container finished with status 137, expected when resource limits are exceeded -> `points = 0.0`
3. A `points` value is parsed from the json file containing the grading results (produced by the grading command)

In all other cases (for example IO exceptions, other docker status codes, etc.) no points are assigned and the submission remains marked as `valid = false`.
