### ISSUE TITLE
Sometimes submissions "just fail" without any obvious reason

### ISSUE THREAD

**Issue by sealexan** [mp-access/Backend-Re#18]
In the frontend, the submission will just fail with "No hint could be provided. This is likely caused by a crash during the execution".
In the backend, a stacktrace such as below will be printed.
I've been unable to determine any correlations, it seems entirely random. It happens both if the workers are on the same host (via a socket) or on another machine.

It seems that the submission docker container dies immediately on its own, hence the stacktrace saying that it could not be killed.

```
^[[30m2021-09-20 22:00:18,575^[[0;39m ^[[39mDEBUG^[[0;39m [398c78b5a0b1a91b] 1 -- [^[[34meval-worker-5^[[0;39m] ^[[33mch.uzh.ifi.access.coderunner.CodeRunner^[[0;39m: Execution of student code took longer than configured timeout. Stopping container e3aa992f190f2f022ca9ae03f907d5b736c8515f7cd4c698d815c4c0858bbb4f
^[[30m2021-09-20 22:00:18,734^[[0;39m ^[[1;31mERROR^[[0;39m [398c78b5a0b1a91b] 1 -- [^[[34meval-worker-5^[[0;39m] ^[[33mch.uzh.ifi.access.coderunner.CodeRunner^[[0;39m: Something unexpected happened while trying to kill the container e3aa992f190f2f022ca9ae03f907d5b736c8515f7cd4c698d815c4c0858bbb4f. It might be that the container stopped right after the timeout limit, but before it could be killed programmatically. Trying to pull info on container...
com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/e3aa992f190f2f022ca9ae03f907d5b736c8515f7cd4c698d815c4c0858bbb4f/kill?signal=SIGKILL: 409, body: {"message":"Cannot kill container: e3aa992f190f2f022ca9ae03f907d5b736c8515f7cd4c698d815c4c0858bbb4f: Container e3aa992f190f2f022ca9ae03f907d5b736c8515f7cd4c698d815c4c0858bbb4f is not running"}

        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2840)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2734)
        at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:783)
        at com.spotify.docker.client.DefaultDockerClient.killContainer(DefaultDockerClient.java:839)
        at ch.uzh.ifi.access.coderunner.CodeRunner.killContainer(CodeRunner.java:184)
        at ch.uzh.ifi.access.coderunner.CodeRunner.startContainerWithTimeout(CodeRunner.java:176)
        at ch.uzh.ifi.access.coderunner.CodeRunner.createAndRunContainer(CodeRunner.java:130)
        at ch.uzh.ifi.access.coderunner.CodeRunner.attachVolumeAndRunBash(CodeRunner.java:82)
        at ch.uzh.ifi.access.student.evaluation.runner.SubmissionCodeRunner.executeSmokeTest(SubmissionCodeRunner.java:83)
        at ch.uzh.ifi.access.student.evaluation.runner.SubmissionCodeRunner.execSubmissionForExercise(SubmissionCodeRunner.java:61)
        at ch.uzh.ifi.access.student.evaluation.process.step.DelegateCodeExecStep.execute(DelegateCodeExecStep.java:50)
        at ch.uzh.ifi.access.student.evaluation.EvalProcessService.executeStep(EvalProcessService.java:100)
        at ch.uzh.ifi.access.student.evaluation.EvalProcessService.fireEvalProcessExecutionAsync(EvalProcessService.java:74)
        at ch.uzh.ifi.access.student.evaluation.EvalProcessService$$FastClassBySpringCGLIB$$ad6fe16d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.cloud.sleuth.instrument.async.TraceAsyncAspect.traceBackgroundThread(TraceAsyncAspect.java:67)
        at jdk.internal.reflect.GeneratedMethodAccessor397.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.PerformanceMonitorInterceptor.invokeUnderTrace(PerformanceMonitorInterceptor.java:62)
        at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:131)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ClientErrorException: HTTP 409 Conflict
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:1044)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1027)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        ... 4 common frames omitted
```

**Comment by ofvalentine** [comment]
Resolved after switching to a different docker client for Java.
